name: Exercice 2

on :

  pull_request:
    paths:
      - '**.yml'
      - '**.yaml'
      - '!test/**'


jobs:
  job_ex2:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Je v√©rifie les fichiers YAML"