name: Afficher mon secret de GitHub
on:
  workflow_dispatch:

jobs:
  exemple-variables:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher mon secret
        run: echo ${{secrets.MON_SECRET}}